/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiagenda;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class AgendaBeranda extends javax.swing.JFrame {
 int input = 0;
    /**
     * Creates new form AgendaBeranda
     */
    public AgendaBeranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        acara = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        tempat = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelAgenda1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Silahkan isi dibawah ini untuk menentukan agendamu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SUDAHKAH MENENTUKAN TUJUAN MU?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel3.setText("Acara/Kegiatan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 96, -1, -1));

        jLabel4.setText("Tanggal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel5.setText("Tempat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setText("Waktu yang diperlukan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel1.add(acara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 209, -1));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 209, -1));
        jPanel1.add(tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 209, -1));

        waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuActionPerformed(evt);
            }
        });
        jPanel1.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 209, -1));

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        tabelAgenda1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Acara/Kegiatan", "Tanggal", "Tempat", "Waktu"
            }
        ));
        tabelAgenda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAgenda1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelAgenda1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 580, 150));

        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jButton4.setText("Ubah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 90, -1));

        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuActionPerformed

    private void tabelAgenda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAgenda1MouseClicked
       DefaultTableModel aplikasi = (DefaultTableModel) tabelAgenda1.getModel();
       acara.setText(aplikasi.getValueAt(tabelAgenda1.getSelectedRow(),0).toString());
       tanggal.setText(aplikasi.getValueAt(tabelAgenda1.getSelectedRow(),1).toString());
       tempat.setText(aplikasi.getValueAt(tabelAgenda1.getSelectedRow(),2).toString());
       waktu.setText(aplikasi.getValueAt(tabelAgenda1.getSelectedRow(),3).toString());
       //berikut adalah code untuuk mengubah data dari user jika tabel diklik salah satunya maka akan lansung menampilkan untuk di edit
    }//GEN-LAST:event_tabelAgenda1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       DefaultTableModel aplikasi = (DefaultTableModel) tabelAgenda1.getModel();
        aplikasi.setValueAt(acara.getText(), tabelAgenda1.getSelectedRow(),0);
        aplikasi.setValueAt(tanggal.getText(), tabelAgenda1.getSelectedRow(),1); 
        aplikasi.setValueAt(tempat.getText(), tabelAgenda1.getSelectedRow(),2);
        aplikasi.setValueAt(waktu.getText(), tabelAgenda1.getSelectedRow(),3);
        //ketika button simpan diklik maka data yang sudah di ubah akan terkirim ke tabel 
        
        acara.setText("");
        tanggal.setText("");
        tempat.setText(""); 
        waktu.setText("");
       //dan kemudian akan mengosongkan seluruh field dengan code ini
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        tabelAgenda1.setValueAt(acara.getText(), input , 0);
        tabelAgenda1.setValueAt(tanggal.getText(), input , 1);
        tabelAgenda1.setValueAt(tempat.getText(), input , 2);
        tabelAgenda1.setValueAt(waktu.getText(), input , 3);
        input=input+1;
        //ini adalah code untuk menambahkan hasil inputan user
        acara.setText("");
        tanggal.setText("");//ketika button diklik maka mengosongkan field
        tempat.setText(""); 
        waktu.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel aplikasi = (DefaultTableModel) tabelAgenda1.getModel();
         if (tabelAgenda1.getSelectedRowCount()==1){
             aplikasi.removeRow(tabelAgenda1.getSelectedRow());
             JOptionPane.showMessageDialog(this,"Agenda berhasil di hapus");
         }else{
            JOptionPane.showMessageDialog(this,"Tidak ada agenda yang dipilih");
         }// button untuk menghapus agenda yang dipilih user
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        // keluar dari program
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaBeranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acara;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelAgenda1;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tempat;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
}
